.coveragerc
.gitignore
README.rst
adwords_client/adwordsapi/operations.py
adwords_client/client.py
adwords_client/utils.py
requirements.txt
tests/doctests/basic_usage.rst
tox.ini

- Adding creation operations to client
- Adding basic usage doctests
- Improving some function names
- Using type hints to perform adwords types casting

Objects creation

---

.gitignore
.travis.yml
adwords_client/__init__.py
adwords_client/adwordsapi/__init__.py
adwords_client/adwordsapi/batch_job_service.py
adwords_client/adwordsapi/common.py
adwords_client/adwordsapi/managed_customer_service.py
adwords_client/adwordsapi/report_downloader.py
adwords_client/client.py
adwords_client/mappers/redshift.py
adwords_client/sqlite.py
requirements.txt
setup.py
tests/doctests/basic_usage.rst
tox.ini

- Upgrading to a newer version of the google client
- Setting up a new way to store operations in our local per-instance sqlite db
- A bit of code cleanup
- Adding a method to retrieve all accounts for a given manager account
- Adding single operation insert

Internal storage

---

adwords_client/adwordsapi/common.py
adwords_client/client.py

Checking for empty operations table and raising an error if there are no operations. Maybe should simply return?

checking if operations table is empty, raising an error in case it is

---

.coveragerc
.gitignore
adwords_client/adwordsapi/common.py
adwords_client/adwordsapi/operations.py
adwords_client/client.py
adwords_client/utils.py
pytest.ini
tests/test_unit.py
tox.ini

- The new internal storage format had some issues when getting the negative id range we could use to create new objects, fixing that.
- Adding location for campaigns creation.
- Adding language for campaigns creation.
- Using unit test instead of doctests for now.
- Minor fixes when downloading csvs.

Fix internal storage

---

adwords_client/client.py
adwords_client/client_operations.py
adwords_client/mappers/redshift.py
adwords_client/mappers/sqlite.py
adwords_client/utils.py

Renaming map_data to downsync in mappers to keep consistency with upsync. Adding _ to protected methods. Checking types with isinstanceof due to numpy numbers.

using downsync instead of map_data, protecting internal methods

---

adwords_client/adwordsapi/batch_job_service.py
adwords_client/client.py
adwords_client/sqlite.py

Fixing problem of out of order client ids, it was forcing a  upload at every operation for batch jobs.

Out of order

---

adwords_client/adwordsapi/operations.py
adwords_client/client.py
adwords_client/sqlite.py
tests/test_unit.py

- Adding ads creation support to the client

adding ad creation to the client

---

adwords_client/adwordsapi/operations.py
adwords_client/client.py

- Adding support for object removal when creating operations
- Client checks if object had its parent removed and avoid creating another removal operation

Supporting removal

---

adwords_client/client.py
adwords_client/client_operations.py
tests/test_unit.py

- operations medule now is capable of returning values for pool jobs
- wait_jobs now returns the value of the batch jobs
- sqlite mapper treating None's and NaN's when reading from table

Returning wait job results

---

adwords_client/utils.py

- It was returning None to some wrong cases.

trying so solve conversion error

---

adwords_client/adwordsapi/common.py
adwords_client/adwordsapi/operations.py
requirements.txt

Fixing adgroup operation creation when modifying bids. Error added after refactor.

Fixing adgroup bids

---

adwords_client/adwordsapi/batch_job_service.py
adwords_client/adwordsapi/operations.py
adwords_client/client.py
adwords_client/mappers/redshift.py
tests/test_unit.py

typo and some more logging

---

adwords_client/__init__.py
adwords_client/adwordsapi/batch_job_service.py
adwords_client/monkey_patch.py
requirements.txt

Multiple monkey patches to avoid unnecessary double processing. Moved a tiny "hack" that the adwords client used to suds, as well as improved some lookups for suds appenders. Removed useless timing calls from suds.

Speed improvements

---

.travis.yml
adwords_client/adwordsapi/common.py
requirements.txt
setup.py

Fixing errors due to buggous httplib2.

fix problem with latest release of httplib2

---

adwords_client/client.py
requirements.txt
setup.py
tests/test_unit.py

Problem with broken version of googleads.

fixing get_accounts, googleads was broken

---

adwords_client/client.py
adwords_client/reports.py

- Fixing zero impressions error on search term report
- Fixing fork problem for django storages

Fix fork reports

---

adwords_client/client.py

- Upgrading api version
- Pinning googleads version
- Fixing file names filters

Api version

---

adwords_client/adwords_api/operations/adgroup.py
adwords_client/adwords_api/operations/keyword.py

Fixing default adgroup operation status.

Fix adgroups

---

adwords_client/adwords_api/operations/adgroup.py
tests/test_unit.py

- Fixing adgroup bid adjustment
- Testing adgruop bid adjustments
- Improving tests

Fix adgroup bid

---

adwords_client/reports.py

Adding value fields to default fields in adgroups and keywords reports.

Report fields

---

adwords_client/client.py

- If map() returns a generator consumes it.

Consume generator

---

adwords_client/adwords_api/common.py
adwords_client/client.py

Refactoring how `PagedResult` works. Now it can be used directly to deal with the extra parameter `links` that the `ManagedCustomerService` returns.

Account links

---

adwords_client/adwords_api/common.py
adwords_client/client.py

Fixing problem with Temporary storage. Files are deleted when the storage is garbage collected, not when they are closed.

Fix temp storage

---

adwords_client/adwords_api/operations/adgroup.py
adwords_client/adwords_api/operations/campaign.py
tests/test_unit.py

Do not set default status when it is not provided.

Campaign status
